on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
env:
  factorio_password: ${{ secrets.FACTORIO_PASSWORD }}
  factorio_username: ${{ secrets.FACTORIO_USERNAME }}
  FSM_MODPACK_DIR: 'dev_pack'
  FSM_DIR: '../'
  FSM_CONF: '../../conf.toml.example'
jobs:
  test-npm:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: make app/bundle
  test-rust:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: test-rust (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Cargo build and test
        run: |
          cargo build
          cargo test --all
  docker-push:
    needs:  [test-npm, test-rust]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - uses: rlespinasse/github-slug-action@v3.x
      - uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ghcr.io/${{ env.GITHUB_REPOSITORY_SLUG }}:${{ env.GITHUB_REF_SLUG }}
